name: create extension artefact

on:
  push:
    branches: 
      - main
  pull_request:

jobs:
  create_artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v5

      - name: run npm i
        run: npm i

      - name: create chrome artifact
        run: npm run build

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: extension chrome
          path: .output

      - name: clear ./output
        run: rm -rf .output

      - name: create firefox artifact
        run: npm run build:firefox

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: extension firefox
          path: .output